title: Martina Andersen Autorin
description: An author website with a blog
header_text: Martina Andersen
footer_text: Copyright 2020 Maike Andersen
header_feature_image: ../uploads/placeholder4.jpg
bannerheight: 20vmax
logo: ../uploads/logo-website.jpg
favicon: ../uploads/logo-website.jpg
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: Home
    siteurl: https://martinaandersenauthor.netlify.app/home
  - name: Bücher
    siteurl: https://martinaandersenauthor.netlify.app/bücher
  - name: Blog
    siteurl: https://martinaandersenauthor.netlify.app/blog
  - name: Martina
    siteurl: https://martinaandersenauthor.netlify.app/martina
  - name: Kontakt
    siteurl: https://martinaandersenauthor.netlify.app/kontak
